tasks:
  - name: Install AWS CLI

    init: |
      cd /workspace
      curl -fSsl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -qq awscliv2.zip
      sudo ./aws/install --update
      rm awscliv2.zip
      cd $THEIA_WORKSPACE_ROOT

vscode:
  extensions:
    - ms-azuretools.vscode-docker