version: '3.8'

services:
  todos-api:
    build:
      context: ./back-end/todos-api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./back-end/todos-api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
  notification-api:
    build:
      context: ./back-end/notification-api
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./back-end/notification-api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start