version: '3.8'

services:
  todos-api:
    build:
      context: ./back-end/todos-api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - OTEL_SERVICE_NAME=todos-api
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}
    volumes:
      - ./back-end/todos-api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
  notification-api:
    build:
      context: ./back-end/notification-api
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
      - OTEL_SERVICE_NAME=notification-api
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}
    volumes:
      - ./back-end/notification-api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
  weather-api:
    build:
      context: ./back-end/weather-api
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=development
      - OTEL_SERVICE_NAME=weather-api
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}
    volumes:
      - ./back-end/weather-api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start