version: '3.8'

services:
  frontend-web:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - OTEL_SERVICE_NAME=x-app-web
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}
      - AWS_XRAY_DAEMON_ADDRESS=xray-daemon:2000
      - AWS_REGION=us-east-1

    volumes:
      - ./frontend-web:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
  todos-api:
    build:
      context: ./back-end/todos-api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - OTEL_SERVICE_NAME=todos-api
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}
      - AWS_XRAY_DAEMON_ADDRESS=xray-daemon:2000
      - AWS_REGION=us-east-1

    volumes:
      - ./back-end/todos-api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
  notification-api:
    build:
      context: ./back-end/notification-api
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
      - OTEL_SERVICE_NAME=notification-api
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}
      - AWS_XRAY_DAEMON_ADDRESS=xray-daemon:2000
      - AWS_REGION=us-east-1
    volumes:
      - ./back-end/notification-api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
  weather-api:
    build:
      context: ./back-end/weather-api
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=development
      - OTEL_SERVICE_NAME=weather-api
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}
      - AWS_XRAY_DAEMON_ADDRESS=xray-daemon:2000
      - AWS_REGION=us-east-1
    volumes:
      - ./back-end/weather-api:/usr/src/app
      - /usr/src/app/node_modules
  xray-daemon:
    image: amazon/aws-xray-daemon
    ports:
      - "2000:2000/udp"  # Expose UDP port for X-Ray
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=us-east-1
    command:
      - "xray -o -b xray-daemon:2000"